var somafunc = require("./modCalc/soma")
var subfunc = require("./modCalc/sub")
var multifunc = require("./modCalc/multi")
var divfunc = require("./modCalc/div")
console.log(somafunc(2,4), subfunc(2,4),multifunc(2,4),divfunc(2,4))